context:
  version: 10.9.2

package:
  name: ts-node
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/ts-node/-/ts-node-${{ version }}.tgz
  sha256: 0290b8a665925d581da75499425c7156b1f433619af62b0ea51d159c18dff968

build:
  number: 0
  noarch: generic

requirements:
  build:
    - jq
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - ts-node --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: TypeScript execution and REPL for node.js
  homepage: https://github.com/TypeStrong/ts-node
  repository: https://github.com/TypeStrong/ts-node

extra:
  recipe-maintainers:
    - danielnachun
